### PR TITLE
also check one level up for encryption (bsc #976315)

### PR DESCRIPTION
**Pull request by wfeldt**
That's just a tentative first version of the fix.

### CODE REVIEW

**Comment by wfeldt** [comment]
Josef, looking at your code: can the 'crypt_device' key exist and be empty?

**Comment by wfeldt** [comment]
here is a sample target map for reference

```
2016-05-11 16:33:08 <1> 10.0.2.15(3364) [Ruby] bootloader/device_map.rb:124 Filtered target map:
{
  "/dev/sda"=>{
    "unique"=>"3OOL.W8iGvCekDp8", "bus"=>"IDE", "device"=>"/dev/sda", "bios_id"=>"0x80", "vendor"=>"QEMU",
    "model"=>"HARDDISK", "driver"=>"ata_piix", "driver_module"=>"ata_piix",
    "partitions"=>[
      {
        "device"=>"/dev/sda1",
        "name"=>"sda1",
        "used_by_type"=>:UB_NONE, "used_by_device"=>"",
        "udev_path"=>"pci-0000:00:01.1-ata-1-part1",
        "udev_id"=>[
          "ata-QEMU_HARDDISK_QM00001-part1", "scsi-0ATA_QEMU_HARDDISK_QM00001-part1",
          "scsi-1ATA_QEMU_HARDDISK_QM00001-part1", "scsi-SATA_QEMU_HARDDISK_QM00001-part1"
        ],
        "size_k"=>409657, "used_fs"=>:ext4, "detected_fs"=>:unknown, "format"=>true, "create"=>true,
        "mkfs_opt"=>"-O dir_index -m5.0",
        "fs_options"=>{
          "opt_dir_index"=>{
            "option_str"=>"-O dir_index", "option_cmd"=>:mkfs, "option_value"=>true
          },
          "opt_reserved_blocks"=>{
            "option_str"=>"-m", "option_cmd"=>:mkfs, "option_value"=>"5.0"
          },
          "opt_reg_checks"=>{
            "option_str"=>"-c 0 -i 0", "option_cmd"=>:tunefs, "option_value"=>true
          }
        }, "tunefs_opt"=>"-c 0 -i 0", "nr"=>1, "fsid"=>131, "fstype"=>"Linux native", "region"=>[0, 51], "type"=>:primary
      },
      {
        "device"=>"/dev/sda2",
        "name"=>"sda2",
        "used_by"=>[
          {
            "type"=>:UB_LVM, "device"=>"/dev/system"
          }
        ],
        "used_by_type"=>:UB_LVM, "used_by_device"=>"/dev/system",
        "udev_path"=>"pci-0000:00:01.1-ata-1-part2",
        "udev_id"=>[
          "ata-QEMU_HARDDISK_QM00001-part2", "scsi-0ATA_QEMU_HARDDISK_QM00001-part2",
          "scsi-1ATA_QEMU_HARDDISK_QM00001-part2", "scsi-SATA_QEMU_HARDDISK_QM00001-part2"
        ],
        "crypt_device"=>"/dev/mapper/cr_ata-QEMU_HARDDISK_QM00001-part2", "size_k"=>20555167,
        "detected_fs"=>:unknown, "create"=>true, "fstopt"=>"defaults", "enc_type"=>:luks,
        "nr"=>2, "fsid"=>142, "fstype"=>"Linux LVM", "region"=>[51, 2559], "type"=>:primary
      }
    ],
    "size_k"=>20971520, "cyl_size"=>8225280, "cyl_count"=>2610, "sector_size"=>512,
    "label"=>"msdos", "name"=>"sda", "max_logical"=>255, "max_primary"=>4, "type"=>:CT_DISK,
    "transport"=>:ata, "used_by_type"=>:UB_NONE, "used_by_device"=>"",
    "udev_id"=>[
      "ata-QEMU_HARDDISK_QM00001", "scsi-0ATA_QEMU_HARDDISK_QM00001",
      "scsi-1ATA_QEMU_HARDDISK_QM00001", "scsi-SATA_QEMU_HARDDISK_QM00001"
    ],
    "udev_path"=>"pci-0000:00:01.1-ata-1", "dasd_format"=>0, "dasd_type"=>0,
    "proposal_name"=>"1. IDE Disk, 20.00 GiB, /dev/sda, QEMU-HARDDISK"
  }
}
```

**Comment by jreidinger** [comment]
ok, regarding empty key it is more question for storage guys. Example target map is good, can you add it to tests? simple use this ruby value and call on it to_yaml and add it to test/data and then you can mock it and add test for that method.
And there is some complains from rubocop.

**Comment by jreidinger** [comment]
and of course it do not solve multi level encrypting, but it is ok for now

**Comment by jreidinger** [comment]
now LGTM, test works for me, rubocop is happy

**Comment by jreidinger** [comment]
LGTM

**Pull request merged**
