### PR TITLE
ensure mountpoints are set correctly (bsc #929656)

### PR DESCRIPTION
**Pull request by wfeldt**
not tested yet

### CODE REVIEW

**Comment by jreidinger** [comment]
I looks like backport of https://github.com/yast/yast-bootloader/pull/231
LGTM

**Comment by wfeldt** [comment]
the place is wrong, but the idea might hold

**Comment by kobliha** [comment]
You really want to push to Code-11-SP1?

**Comment by wfeldt** [comment]
It's the relevant branch for sp4. Why?

**Comment by wfeldt** [comment]
see next pr

**Pull request closed without merging**
