### PR TITLE
Fix alternative raid

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by wfeldt** [comment]
Josef, could you please fix the English grammar in your comments.

**Comment by jreidinger** [comment]
@wfeldt I try to improve grammar in the comments. If you have something specific in mind, can you please point me to it?

**Comment by wfeldt** [comment]
I would have been happy when you just added the 3rd-person 's'.

You may not believe it but it really sticks out if one reads your comments. If I browse through yast code I immediately know 'ah, that was Josef'.

**Comment by jreidinger** [comment]
@wfeldt OK, that is fair request and I can focus on that single thing.

**Comment by wfeldt** [comment]
'a fair request' :-)

**Pull request merged**
