### PR TITLE
fixed build with storage-ng

### PR DESCRIPTION
**Pull request by aschnell**
Yes, this is primitive but a first step to setup autosubmission.

For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.

### CODE REVIEW

**Comment by jreidinger** [comment]
fine for me if it fixes build for you. Maybe you should also modify somehow Rakefile to avoid accidental send to factory? Of course to make it work, it will need more changes to support at least minimal case.

**Comment by aschnell** [comment]
Working on it. Jenkins setup will be next.

**Comment by ancorgs** [comment]
@aschnell could you add a commit commenting this line in .travis.yml?
```
 - COVERAGE=1 rake test:unit
```
That should turn travis green

**Comment by ancorgs** [comment]
Shouldn't we also add a changelog entry and bump version to 3.3.0?
We did it for the other branched packages to make everything more clear.

I'm fine with doing it in a separate pull request. If that's the case, LGTM.

**Comment by ancorgs** [comment]
Thanks, LGTM

**Pull request merged**
