### PR TITLE
Fix disks_order call

### PR DESCRIPTION
**Pull request by imobach**
@jreidinger I guess it fixes problem when calling disks_order [bsc#975514](https://bugzilla.suse.com/show_bug.cgi?id=975514). Feel free to fix it yourself (as part of your refactoring work) and drop this PR.

Thanks!

### CODE REVIEW

**Comment by teclator** [comment]
LGTM

**Comment by imobach** [comment]
Thanks, I've added some tests to be on the safe side :)

**Comment by jreidinger** [comment]
gj, thanks.

**Comment by imobach** [comment]
Welcome!

**Pull request merged**
