### PR TITLE
Propose secure_boot by default only on x86

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by jreidinger** [comment]
what is reason to not propose secure boot on other architectures? ( I think only arm is now affected )

**Comment by andreas-schwab** [comment]
"/usr/sbin/shim-install: no such file or directory" from perl-bootloader

**Comment by jreidinger** [comment]
so it means that it is not valid option on arm?

**Comment by andreas-schwab** [comment]
Not for now.

**Comment by jreidinger** [comment]
It changing only proposal, so in UI it is still possible to enable it?

**Comment by andreas-schwab** [comment]
There is currently no way to toggle secure boot in the UI

**Comment by jreidinger** [comment]
OK, so LGTM

**Comment by jreidinger** [comment]
Please add entry to changelog and increase version in spec ile. Then I merge it.
Thanks

**Pull request merged**
