### PR TITLE
ensure libstorage runs in 'normal' mode so it really returns us the m…

### PR DESCRIPTION
**Pull request by wfeldt**
…ountpoints (bsc #929656)

### CODE REVIEW

**Comment by wfeldt** [comment]
this seems to fix part 1 of the problem: we how have the mountpoints

**Comment by wfeldt** [comment]
but there's more that's wrong

**Comment by jreidinger** [comment]
For code 11 it looks OK.

**Comment by wfeldt** [comment]
The change will not be needed in sle11-sp4. See discussion in bugzilla.

**Pull request closed without merging**
