### PR TITLE
Quick fix for unit tests: Move broken tests out of the way

### PR DESCRIPTION
**Pull request by shundhammer**
Since "rake test:unit" also recurses into subdirectories of test/, I moved the tests that are currently broken due to storage-ng changes out of the way.

In order to be able to run individual broken tests to fix them, I added a symlink to test_helper.rb in ../test .

### CODE REVIEW

**Comment by ancorgs** [comment]
Instead of moving the files, it would be probably more "polite" to disable the tests by changing
```ruby
it "whatever" do
 blah
end
```
into
```ruby
xit "whatever" do
  blah
end
```
See https://relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples#temporarily-pending-by-changing-%22it%22-to-%22xit%22

**Comment by ancorgs** [comment]
I meant, using "xit" or "pending" or any of the 4 mechanisms described in the link

**Comment by jreidinger** [comment]
another way is to not end file with `_test.rb` and instead you can use `_test_not_ready.rb`. see https://github.com/yast/yast-rake/blob/master/lib/tasks/test_unit.rake

**Comment by ancorgs** [comment]
Not sure whether you want to merge already or whether you are planning to add some storage-ng mocking to this same PR.

In the former case, it LGTM as it is.

**Comment by shundhammer** [comment]
This PR is obsoleted by https://github.com/yast/yast-bootloader/pull/387 . Closing.

**Pull request closed without merging**
