### PR TITLE
fix device name by-path handling (bsc #976228)

### PR DESCRIPTION
**Pull request by wfeldt**
The relevant keys in Storage::GetTargetMap() are named 'udev_path', not 'path'.

### CODE REVIEW

**Comment by jreidinger** [comment]
thanks for fix...it used to work on past or never worked?

**Comment by jreidinger** [comment]
LGTM

**Comment by wfeldt** [comment]
ISTR that the target map entry names changed a bit at some point in time

**Comment by aschnell** [comment]
That change must have been a looong time ago.

**Comment by wfeldt** [comment]
Hm, git blame says the code was done in one go. So it looks just like a plain bug.

**Comment by wfeldt** [comment]
... and never worked

**Pull request merged**
