### PR TITLE
try tracking feature of simplecov

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by mvidner** [comment]
This looks good but we should describe it better - link to https://github.com/colszowka/simplecov/pull/422 
Also I want to understand what happens with https://coveralls.io/builds/9582948/source?filename=src%2Flib%2Fbootloader%2Fauto_client.rb

**Comment by jreidinger** [comment]
@mvidner it is fine for me to have link, but I do not like referencing pull request as it can change later. I think better to reference configuration where is documentation like https://github.com/colszowka/simplecov/blob/master/lib/simplecov/configuration.rb#L53

regarding auto_client I am not sure. I will try it locally what it will report.

**Comment by jreidinger** [comment]
@mvidner OK, now I reproduce it locally. Reason is simple. If we require everything, then simplecov mark all lines that are run during require ( like class and method definitions ) as test covered ( as it will fail if there is a problem ). But now it is not required, so if there is some problem it won't be detected, so it is not covered. Does it make sense?

**Comment by mvidner** [comment]
OK, so the auto client is simply not covered.

Linking to specific line numbers on a symbolic reference like `master` will also break. How about this for the commit message:

> Switched to Simplecov.track_files to know about files that contain only untested code
>
> http://www.rubydoc.info/gems/simplecov/SimpleCov/Configuration#track_files-instance_method
>
> Previously we implemented this ourselves by loading all files but that produced false negatives for code that called a method without requiring its file.

**Pull request merged**
