### PR TITLE
Use shared RSpec examples for CWM widgets

### PR DESCRIPTION
**Pull request by mvidner**

### CODE REVIEW

**Comment by mvidner** [comment]
Using https://github.com/yast/yast-yast2/pull/555

**Comment by mvidner** [comment]
Ugh, in Travis I get a ExpiredTestDoubleError and I have no idea how that appears.

**Comment by jreidinger** [comment]
@mvidner my idea is that widget need to return some value some mocking and it is missing there, and instead double from other test is used. Btw see my LabeledWidget shared example which looks similar to your attempt.

**Comment by jreidinger** [comment]
yast2 already have rspec test, can you please rebase it? then I will merge it.

**Pull request merged**
