### PR TITLE
Skip grub2 update

### PR DESCRIPTION
**Pull request by jreidinger**
new translatable string is not problem as it is already used at different location.

### CODE REVIEW

**Comment by wfeldt** [comment]
Would it make sense to also check for boot_common in
https://github.com/yast/yast-bootloader/blob/master/src/modules/BootGRUB2.rb#L207
?

**Comment by wfeldt** [comment]
I meant boot_custom

**Comment by jreidinger** [comment]
@wfeldt yes, it make sense to fix also this, will add it.

**Comment by jreidinger** [comment]
@wfeldt done

**Comment by wfeldt** [comment]
logic ok with be, but you'll need to make rubocup happy

**Comment by wfeldt** [comment]
ok now

**Pull request merged**
