### PR TITLE
fix extended typo (thanks mvidner)

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by mvidner** [comment]
Code looks good, but we still have a hole in code coverage: 
https://coveralls.io/builds/6134237/source?filename=src%2Flib%2Fbootloader%2Fstage1.rb#L345
should we fix it right now?

**Comment by jreidinger** [comment]
@mvidner I need specific target map that have /boot on logical partition to test it for real.

**Comment by mvidner** [comment]
I think I have such a machine at home, running 13.2. Will it work if I run `Yast::Storage.GetTargetMap` and dump that to YAML?

**Comment by jreidinger** [comment]
@mvidner yes, then I will add it, but I prefer to release fix soon and then add test when you dump it

**Comment by mvidner** [comment]
Sounds good!
LGTM.

**Comment by mvidner** [comment]
(This is Pull Řequest numbeř Třista třicet tři! We Řule!)

**Pull request merged**
