### PR TITLE
Secure boot arm

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by ggardet** [comment]
> cannot merge now as shim and mokutil is x86_64 only.

And there will be no shim for aarch64. Here is my PR (untested yet): https://github.com/yast/yast-bootloader/pull/565

**Comment by jreidinger** [comment]
@ggardet how it can work without shim? I probably need more details to know about how it should work ( ideally some persistent URL, so I can link it from code for future references.

**Comment by ggardet** [comment]
> @ggardet how it can work without shim? I probably need more details to know about how it should work ( ideally some persistent URL, so I can link it from code for future references.

The only problem I have is that signed grub is loaded properly, but is not configured. 
I still need to figure out how to fix it.

**Comment by jreidinger** [comment]
replaced by https://github.com/yast/yast-bootloader/pull/565

**Pull request closed without merging**
