### PR TITLE
Autoyast validation documentation

### PR DESCRIPTION
**Pull request by imobach**
Some documentation about AutoYaST validation. Also I've updated the spec and changes file.

### CODE REVIEW

**Comment by gabi2** [comment]
Is this intended: imobach wants to merge 2 commits into autoyast-validation from autoyast-validation-doc?

**Comment by imobach** [comment]
@gabi2 Yes, it's intended (weird, but intended :) ).

**Comment by gabi2** [comment]
LGTM

**Comment by imobach** [comment]
@gabi2 Thanks!

**Pull request merged**
